### ISSUE TITLE
New and Short link scheme

### ISSUE THREAD

**Issue by MarauderXtreme** [MarauderXtreme/video-game-radiostation-playlists#13]
We found out that you can shorten the links to the playlists.

### For Spotify:  
https://open.spotify.com/user/marauderxtreme/playlist/5PnixK1xU6OcuZfGDR6US4  
_becomes_  
https://open.spotify.com/playlist/5PnixK1xU6OcuZfGDR6US4  
**and**
https://embed.spotify.com/?uri=spotify%3Auser%3Amarauderxtreme%3Aplaylist%3A5PnixK1xU6OcuZfGDR6US4  
_becomes_  
https://open.spotify.com/embed/playlist/5PnixK1xU6OcuZfGDR6US4

### For Apple Music:  
https://itunes.apple.com/de/playlist/gta-san-andreas-sf-ur/idpl.c4f19686b2e9436087e5c221d1b4e242  
_becomes_
https://itunes.apple.com/playlist/pl.c4f19686b2e9436087e5c221d1b4e242

This issue is a good starting point for everyone with enough free time.

**Comment by h4llow3En** [comment]
Also the embedded versions of apple music should look like
https://tools.applemusic.com/embed/v1/playlist/pl.c4f19686b2e9436087e5c221d1b4e242

**Comment by saskiagrun** [comment]
I'm on it!

**Comment by MarauderXtreme** [comment]
@saskiagrun I've seen that you forked the repo a few days ago. To make it easier to merge later could you rebase your fork on the latest master?

**Comment by MarauderXtreme** [comment]
Closed by #16 #17 #18 and #19
Thanks for the help @saskiagrun
